<script>
    require(['jquery'], function($){
        $(document).ready(function() {
            var customurl = "<?php echo $this->getUrl().'test/index/index'?>";
            $.ajax({
                url: customurl,
                type: 'POST',
                dataType: 'json',
                complete: function(response) { 
                    userdata  = response.responseJSON;
                    if(!userdata.response) {
                        console.log("ddddd");
                        $(".customer-welcome").hide();
                        $(".link.authorization-link").show();
                    } 
                }
            })
        });
    });
</script>